### ISSUE TITLE
Sessions do not persist after Express server restart

### ISSUE THREAD

**Issue by ZeshanA** [ZeshanA/dashboard#1]
Will likely need to Implement database storage to allow for sessions that persist through server restarts - which, obviously, occur quite often in development and currently require a reauth with Monzo following every line of code changed.

**Comment by Sterbic** [comment]
Can't you set up some kind of CI to reauth with Monzo automatically every time you deploy a new version?

**Comment by ZeshanA** [comment]
Maybe use SQLite or store access tokens in cookies on client side.
