### ISSUE TITLE
Entries in transaction table have no currency symbol

### ISSUE THREAD

**Issue by ZeshanA** [ZeshanA/dashboard#2]
This issue can be resolved by adding string representations of amounts (e.g. £143) to all transactions after fetching them. Would be a good idea to add decimal points into this string also.

**Comment by Sterbic** [comment]
Is this for the data storage or for the presentation layer? If it's for the storage you definitely want to store value and currency type separately. Say I want to know the total number of pounds across all users of the platform, it should be as easy as:
```
SELECT sum(value) FROM balances_all_users WHERE currency = 'GBP'
```

**Comment by ZeshanA** [comment]
Monzo/Starling only operate in GBP, so we can assume every transaction amount is in pounds by default.

I’m planning to use this JavaScript API to add the correct formatting on the client side: https://www.reddit.com/r/javascript/comments/7zo37w/tip_tolocalestring_is_a_great_way_to_format/?st=JE9XHHT1&sh=ca363dc5
